# linalg 서브모듈 사용하여 선형대수 연산하기

In [1]:
import numpy as np

역행렬 구하기

np.linalg.inv
- 모든 차원의 값이 같아야함.

In [16]:
x = np.random.randn(3, 3)

print(x)

xi = np.linalg.inv(x)
print(xi)

z = np.eye(3)

[[ 1.41616091  0.37911384 -1.24706923]
 [-0.19585108  0.37602524  1.3749202 ]
 [-0.62638335 -1.3272995   2.22411846]]
[[ 0.89020256  0.27163131  0.33122015]
 [-0.14237562  0.7922966  -0.56961752]
 [ 0.16574341  0.54932335  0.20296479]]


In [17]:
np.allclose(x@xi, z)

True

In [4]:
#행렬의 곱은 연산자 @
# 혹은 np.matmul(행렬, 행렬)

x @ np.linalg.inv(x)

array([[ 1.00000000e+00, -1.34423082e-15, -2.42931202e-16],
       [ 7.50389554e-17,  1.00000000e+00,  8.09095859e-17],
       [ 3.95779282e-16,  7.21731093e-16,  1.00000000e+00]])

 np.linalg.solve

- Ax = B 형태의 선형대수식 솔루션을 제공

In [7]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B) #x+y = 25, 2x+4y = 64 인 연립방정식을 리턴해줌.
print(x)

[18.  7.]


In [9]:
#오차가 존재할 수 있으나, np.allclose(A, B)를 통해 True, False 형태로 오차가 무시가능할 정도로 작은 같은 행렬인지 알려줌.
np.allclose(A@x, B)

True