# ndarray 기본함수 사용하기

numpy.org에서 공식문서 볼 수 있음.

In [2]:
import numpy as np

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)

In [4]:
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.57294277 0.57575642 0.12092658 0.56511091 0.06414454]
 [0.71332063 0.94810891 0.99728911 0.49273037 0.37973259]
 [0.96897089 0.76418038 0.94478035 0.58757765 0.67499326]]


ndarray끼리의 연산은 기본적으로 size가 동일해야함.

In [5]:
np.add(x,y)

array([[ 0.57294277,  1.57575642,  2.12092658,  3.56511091,  4.06414454],
       [ 5.71332063,  6.94810891,  7.99728911,  8.49273037,  9.37973259],
       [10.96897089, 11.76418038, 12.94478035, 13.58757765, 14.67499326]])

In [6]:
np.subtract(x,y)

array([[-0.57294277,  0.42424358,  1.87907342,  2.43488909,  3.93585546],
       [ 4.28667937,  5.05189109,  6.00271089,  7.50726963,  8.62026741],
       [ 9.03102911, 10.23581962, 11.05521965, 12.41242235, 13.32500674]])

In [7]:
np.multiply(x,y)

array([[ 0.        ,  0.57575642,  0.24185316,  1.69533273,  0.25657816],
       [ 3.56660314,  5.68865345,  6.9810238 ,  3.94184294,  3.41759334],
       [ 9.68970887,  8.4059842 , 11.33736423,  7.63850948,  9.44990563]])

In [8]:
np.divide(x,y)

array([[ 0.        ,  1.7368456 , 16.53896131,  5.3086924 , 62.35916577],
       [ 7.00947065,  6.32838691,  7.01902779, 16.23606039, 23.70088889],
       [10.3202275 , 14.39450719, 12.70136489, 22.12473527, 20.74094786]])

In [9]:
x + y

array([[ 0.57294277,  1.57575642,  2.12092658,  3.56511091,  4.06414454],
       [ 5.71332063,  6.94810891,  7.99728911,  8.49273037,  9.37973259],
       [10.96897089, 11.76418038, 12.94478035, 13.58757765, 14.67499326]])

In [10]:
x - y

array([[-0.57294277,  0.42424358,  1.87907342,  2.43488909,  3.93585546],
       [ 4.28667937,  5.05189109,  6.00271089,  7.50726963,  8.62026741],
       [ 9.03102911, 10.23581962, 11.05521965, 12.41242235, 13.32500674]])

In [11]:
x * y

array([[ 0.        ,  0.57575642,  0.24185316,  1.69533273,  0.25657816],
       [ 3.56660314,  5.68865345,  6.9810238 ,  3.94184294,  3.41759334],
       [ 9.68970887,  8.4059842 , 11.33736423,  7.63850948,  9.44990563]])

In [12]:
x / y

array([[ 0.        ,  1.7368456 , 16.53896131,  5.3086924 , 62.35916577],
       [ 7.00947065,  6.32838691,  7.01902779, 16.23606039, 23.70088889],
       [10.3202275 , 14.39450719, 12.70136489, 22.12473527, 20.74094786]])

In [13]:
print(y)

[[0.57294277 0.57575642 0.12092658 0.56511091 0.06414454]
 [0.71332063 0.94810891 0.99728911 0.49273037 0.37973259]
 [0.96897089 0.76418038 0.94478035 0.58757765 0.67499326]]


In [15]:
np.mean(y)

0.6247043574326286

In [16]:
y.mean()

0.6247043574326286

In [18]:
np.max(y)

0.9972891138342862

In [19]:
y.max()

0.9972891138342862

In [20]:
np.argmax(y) #max값을 갖는 인자의 index를 행을 기준으로 세어서 몇번째인지 return 해줌.

7

In [21]:
np.var(y), np.median(y), np.std(y) #마지막 함수는 표준편차

(0.07664439739901331, 0.5875776520328234, 0.2768472456048882)

In [24]:
y.sum() #axis의 기본값이 None으로 들어가있음. 축을 명시하면 그 축을 따라 sum을 구해줌. ex) axis = 1

9.37056536148943

In [23]:
y.cumsum() # 누적 합계를 index 별로 알려줌. 앞에서부터 차례로 더해감.

array([0.57294277, 1.14869919, 1.26962577, 1.83473668, 1.89888122,
       2.61220185, 3.56031075, 4.55759987, 5.05033024, 5.43006283,
       6.39903372, 7.1632141 , 8.10799445, 8.6955721 , 9.37056536])

In [25]:
z = np.random.randn(10)
print(z)

[ 0.38422838  0.96398476 -0.18046945 -1.78650275 -0.37365173  1.3022601
  0.35467773 -1.56073323 -0.32024575  0.31113867]


In [26]:
np.any(z > 0) #z의 원소중 하나만 맞아도 참임

True

In [27]:
np.all(z > 0)

False

In [28]:
np.all(z != 0)

True

In [30]:
l = np.random.randn(10)
print(l)

[-0.97356195 -1.12682432 -0.02417614  1.64622959  1.32643967 -0.91549925
 -0.79022702 -0.90608875 -0.28712718 -0.18687526]


In [31]:
#ex. 이중에서 음수인건 0으로 바꿀 것임
#np.where(조건, 참인 경우, 거짓인 경우)

np.where(z>0, z, 0)

array([0.38422838, 0.96398476, 0.        , 0.        , 0.        ,
       1.3022601 , 0.35467773, 0.        , 0.        , 0.31113867])