# ndarray 데이터 생성하기(numpy 모듈 함수 이용)

In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
x = np.array([1,2,3,4])
print(x)

y = np.array([[2,3,4],[1,2,5]])

print(y)
print(type(x))
print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [18]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.empty((3,4))

array([[1.20958938e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.94878778e+179, 6.18606660e+169,
        2.70388533e-056],
       [1.58661304e-047, 2.67611206e+184, 2.77438503e+180,
        2.98713147e-032]])

In [23]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [26]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [29]:
x = np.arange(1, 1)
print(x)

x.shape

x.reshape(3, 5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])