# ndarray 인덱싱 & 슬라이싱 이해하기

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
x[-1]

9

In [5]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
x[0]

array([0, 1, 2, 3, 4])

In [7]:
x[0][1]

1

In [8]:
x[0,1]

1

In [10]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [11]:
x[1, 1, 2]

17

In [12]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
x[0, 1]

array([3, 4, 5])

In [14]:
x[0, 0, 0]

0

In [15]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [17]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
x[:,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [19]:
x[1, 1:4]

array([6, 7, 8])